# Site settings
title: BioPerl
email: bioperl-l@mailman.open-bio.org
description: The Bioperl Project is an international association of developers of open source Perl tools for bioinformatics, genomics and life science. It is supported by the <a href='http://www.open-bio.org/wiki/Main_Page'>Open Bioinformatics Foundation</a>.
baseurl: "http://bioperl.github.io"
url: "http://bioperl.github.io"
twitter_username: bioperl
github_username: bioperl
encoding: UTF-8
# Build settings
# converters: kramdown (default), maruku (deprecated), redcarpet, rdiscount
# rdiscount partially formats the '''perl blocks, no highlighting
# kramdown does not format Perl correctly, the blocks are not recognized
markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,mkd,md
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", 
               "fenced_code_blocks", "no_intra_emphasis", "quote"]


