# Site settings
title: BioPerl
email: bioperl-l@mailman.open-bio.org
description: The Bioperl Project is an international association of developers of open source Perl tools for bioinformatics, genomics and life science
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
encoding: UTF-8
# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,mkd
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]